### ISSUE TITLE
💡 [IMPROVEMENT] - Make it clear what OpenTofu is without referring to Terraform

### ISSUE THREAD

**Issue by MetalPinguinInc** [opentofu/opentofu.org#261]
### Summary

I ran into a post announcing "OpenTofu is going GA" on Lemmy and clicked the link out of curiosity to be brought to the OpenTofu website. The only context I had was that OpenTofu is a FOSS application, but not what kind of application. With this lack of context and no familiarity with Terraform, it is completely unclear what OpenTofu does. The 2 places I could eventually find this information were the docs and the Terraform website.

It is great to advertise the values of the project, but don't forget that visitors might only know the name of your product out of context. For someone who has never heard of either Terraform or OpenTofu, the website is trying to "sell" me an alternative to a product I don't know, for reasons I fully agree with. This is very confusing.

### Basic Example

The only mention of OpenTofu's functionality is "The open source infrastructure as code tool." tagline. The FAQ question: "What is OpenTofu?" is answered with: "A drop-in replacement for Terraform".

If you look at the Terraform website it provides a quick overview of what it does and some common use-cases. The latter is especially useful for someone who stumbles upon your website.

### Drawbacks

I suppose it could make people who are intimately familiar with Terraform have the opposite experience: they know what OpenTofu does, but not why they should use it instead of Terraform

**Comment by janosdebugs** [comment]
Hey @MetalPinguinInc ! I think you are right, the messaging so far is geared towards people who already use Terraform and there is a wider audience for the website.

Personally, I'd like to see a few changes, but none of these have been agreed upon:

- Restructure the menu to make it easier to find documentation as the Manifesto, I believe, has served its purpose.
- Add something to help newcomers understand how the whole state management works as that seems to be the most confusing aspect of OpenTofu and Terraform. (i.e. ideally, you are not supposed to touch TF-provisioned infrastructure by hand at all). 
- As you point out, rebuild the front page and FAQ to bring people from outside the ecosystem in.
- Make the website as accessible as possible (See #259 and #260).

That being said, these are longer term plans and there's a lot that can be done right now. If there's, for example, a piece of text you think should be changed, please open an issue because that's easier to make a quick decision on.

Thank you so much for your detailed issue and your help. Your input is very valuable.
